Refactor code and add documentation
Morazzer/cookies-mod pull request #44
Opened 2023-10-29 14:25 UTC by Morazzer

2023-10-29 16:00 UTC, DreamTexX requested changes
This PR is huge. I will not review each file, but these are the most common things i found:

- You frequently alternate between "get/gets", "change/changes", and "create/creates". Please use only one form consistently, for example: "Get**s** the value in string form".
- You document methods that may not require documentation, specifically a description. However, it is important to always include parameter descriptions. While my knowledge of Java documentation standards may be limited, based on this example, a description is not necessary as the method name is sufficiently descriptive.
```java
/**
 * (no description needed in my opinion)
 * @param selected The selected element.
 */
public void setSelected(T selected) {}
```
- I started marking every occurrence, but u often lack punctuation marks. As i already made 15+ comments about this, I will not continue to mark this. You will find it yourself.

I only focused on documentation, not on any kind of logic.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/ProfileViewerCommand.java
> + * Command to open the profile viewer (currently not implemented)
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/arguments/PlayerNameArgument.java
> +     * Parser to get a valid sting username from the input.
Typo, "string"

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/arguments/PlayerNameArgument.java
> +     * Suggestions for the player names
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/arguments/PlayerNameArgument.java
> +     * @return A future for the suggestions which will almost ever be completed.
I would strip out the complete last part. Its unnecessary information. "A future that will resolve to the suggestions."

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/arguments/RealIdentifierArgument.java
> + * Not that you might want to use a thread save version of the {@linkplain java.util.Collection} type for this to avoid {@linkplain java.util.ConcurrentModificationException}s.
I think you mean "Note"?

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/arguments/RealIdentifierArgument.java
> +     * Suggestions the identifiers
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/arguments/RealIdentifierArgument.java
> +     * @return A future for the suggestions which will almost ever be completed.
Again, "A future that will resolve to the suggestions"

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/arguments/RealIdentifierArgument.java
> +     * Used to create a string array with a default namespace and a prefixed path
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/arguments/RealIdentifierArgument.java
> +     * @param id The identifier in string form
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/arguments/RealIdentifierArgument.java
> +     * @return A string array representing the namespace at [0] and the path at [1]
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/dev/subcommands/DisableToolsSubcommand.java
> + * Subcommand for disabling enabled "devtools" in the {@linkplain dev.morazzer.cookiesmod.utils.DevUtils} class.
"Subcommand to disable devtools [...]"

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/dev/subcommands/EnableToolsSubcommand.java
> + * Used to enable disabled "devtools" in the {@linkplain dev.morazzer.cookiesmod.utils.DevUtils} class.
"Subcommand to enable devtools [...]"

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/dev/subcommands/TestSubcommand.java
> + * Subcommand to add various methods to the command tree, these methods have to be annotated with the {@linkplain dev.morazzer.cookiesmod.commands.dev.subcommands.TestEntrypoint} annotation
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/helpers/ClientCommand.java
> +     * @return All aliases
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/commands/helpers/LoadCommand.java
> + * The purpose for this annotation is to load all classes that have this annotation present and extend {@linkplain dev.morazzer.cookiesmod.commands.helpers.ClientCommand}.
"purpose of this annotation [...] all annotated classes and [...]"

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/categories/about/AboutEditor.java
> +     * Create a new editor.
"Create**s**"

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/categories/about/AboutOption.java
> + * The option that describes the {@linkplain dev.morazzer.cookiesmod.config.categories.about.credits.Credits} section
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/categories/about/credits/Descriptions.java
> + * A list of descriptions that if met will allow a person to be listed in the credit section
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/categories/about/credits/Person.java
> +     * Creates a new instance of a person from a json object
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/system/Option.java
> +     * Create a new option
Consistency, missing punctuation marks.
"Creates" or "Constructor to create a new option."

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/system/Option.java
> +    }
Basically tags? If yes i would consider renaming it to "tags".

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/system/Option.java
> +     * Returning false will disable calls to {@link Option#save()} and {@link Option#load(com.google.gson.JsonElement)}
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/SliderEditor.java
> +     * Get the value in string form
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/system/options/ButtonOption.java
> + * A simple button in the config
Consistency, missing punctuation marks.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/system/options/SliderOption.java
> +     * Set a minimum for the value, it can't get lower than this.
Is this value inclusive or exclusive? Should be clarified here.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/system/options/SliderOption.java
> +     * Set a maximum for the value, it can't get higher than this.
Is this value inclusive or exclusive? Should be clarified here.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/system/options/SliderOption.java
> +     * Set the value of the option.
Is it possible to exploit min/max boundaries with this method? What will happen when u set an invalid (out of boundary) value? Should be clarified.

2023-10-29 16:00 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/config/system/parsed/ConfigReader.java
This class represents what i mean with "unnecessary descriptions". I think it would be perfectly fine if you only describe the parameters most of the time.

2023-10-29 16:02 UTC, DreamTexX commented
Additional to that comment:
> You frequently alternate between "get/gets", "change/changes", and "create/creates". Please use only one form consistently, for example: "Gets the value in string form".

I would prefer "Get**s**", "Change**s**" and "Create**s**"

2023-10-29 16:52 UTC, zFlxw requested changes
Since after around 80 files, it takes 4-5 seconds just to load the diff, I stopped reviewing after ~120 files.

As already mentioned, please fix the inconsistent documentation style throughout the project. Besides that, check through my comments as there are a few annotations related to other things than this type of documentation.

And also, please never ever propose such a big pull request again. GitHub is completely lagging and it takes ages to write a comment to the code. Just structure your changes into smaller pull requests that are easier to review. :)

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/ColorEditor.java
> +            //context.drawTexture(COLOR_OPACITY, overlayX + 90, overlayY + 5, 0, 0, 10, 64, 10, 64);
I suggest removing this line as you have the old code in version control now.

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/ConfigOptionEditor.java
> +     * Create a new option editor.
```suggestion
     * Creates a new option editor.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/ConfigOptionEditor.java
> +     * Get the height of the option.
```suggestion
     * Gets the height of the option.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/ConfigOptionEditor.java
> +     * Get the height of the option.
```suggestion
     * Gets the height of the option.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/ConfigOptionEditor.java
> +     * Render the editor.
```suggestion
     * Renders the editor.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/ConfigOptionEditor.java
> +     * @return Rather or not, the option matches the parameter.
```suggestion
     * Checks whether the option matches a user-defined search parameter.
     *
     * @param search The search parameter.
     * @return Whether the option matches the parameter.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/ConfigOptionEditor.java
> +     * @return If there is a dragged element.
```suggestion
     * Whether there is currently an element that is being dragged in the editor.
     *
     * @return Whether there is a dragged element.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/ConfigOptionEditor.java
> +     * Get the {@linkplain net.minecraft.client.font.TextRenderer} instance.
```suggestion
     * Gets the {@linkplain net.minecraft.client.font.TextRenderer} instance.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/SliderEditor.java
> +     */
```suggestion
    /**
     * Gets the value as string.
     *
     * @return The value as string.
     */
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/editor/SliderEditor.java
> +     * Save the current value to the option instance and update the text field.
```suggestion
     * Saves the current value to the option instance and updates the text field.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/element/ButtonElement.java
> + * Gui element that works as a button.
```suggestion
 * GUI element that works as a button.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/element/ButtonElement.java
> +     * Create a new button that can be rendered everywhere.
```suggestion
     * Creates a new button that can be rendered everywhere.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/element/ButtonElement.java
> +     * Render the button onto the current draw context.
```suggestion
     * Renders the button onto the current draw context.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/element/ButtonElement.java
> +     * Check if the mouse click occurred above the button and if so, then execute the runnable.
```suggestion
     * Checks if the mouse click occurred above the button and executes the runnable if so.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/element/DropdownElement.java
> + * Gui element to render a dropdown menu everywhere.
```suggestion
 * GUI element to render a dropdown menu everywhere.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/element/DropdownElement.java
> +     * Create a new dropdown element.
```suggestion
     * Creates a new dropdown element.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/element/DropdownElement.java
Refactor the not-annotated comments with the same schema as the mentioned ones.

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/element/SwitchElement.java
Same here, all imperatives should be refactored as "checks ...", "gets ...", etc.

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/options/BooleanOption.java
> +     * Add a hud element to the button, this element will only be visible if the button is toggled on.
```suggestion
     * Adds a HUD element to the button. This element will only be visible when the button is toggled on.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/options/DraggableListOption.java
> +     * Add a value supplier to the option to correctly map the strings to their respective display variant.
```suggestion
     * Adds a value supplier to the option to correctly map the strings to their respective display variant.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/options/KeybindingOption.java
> +     * Set a default key that is different from the initial key.
```suggestion
     * Sets a default key that is different from the initial key.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/options/SliderOption.java
Refactor imperatives in documentation.

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/parsed/ConfigProcessor.java
Refactor imperatives in documentation.

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/parsed/ConfigReader.java
Refactor imperatives in documentation.

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/parsed/ProcessedCategory.java
Refactor imperatives in documentation.

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/config/system/parsed/ProcessedOption.java
> +     * Create a processed option.
```suggestion
     * Creates a processed option.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/features/farming/garden/Garden.java
> +     * @return If the player is on the garden.
```suggestion
     * Checks whether the player is currently on the garden.
     *
     * @return Whether the player is on the garden.
```

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/features/farming/garden/Plot.java
> +     */
I suggest replacing the "if ..." by "whether ..." for grammatical reasons.

2023-10-29 16:52 UTC, zFlxw commented on src/main/java/dev/morazzer/cookiesmod/features/farming/garden/YawPitchDisplay.java
> + *
Well, that's an interesting class description 🤔

2023-10-30 13:04 UTC, zFlxw submitted a review, later dismissed
I have not re-reviewed every single file, but overall it LGTM.

2023-10-30 17:32 UTC, DreamTexX requested changes
I have now reviewed each change and feel that there are a few minor adjustments that need to be made.

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/events/api/PlayerListUpdateEvent.java
> +     * Spread an event to all the subscribed listeners.
```suggestion
     * Distribute an event to all the subscribed listeners.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/events/api/PlayerListUpdateEvent.java
> +    static PlayerListUpdateEvent spread(PlayerListUpdateEvent[] playerListUpdateEvents) {
```suggestion
    static PlayerListUpdateEvent distribute(PlayerListUpdateEvent[] playerListUpdateEvents) {
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/features/farming/garden/RancherBootsOverlay.java
> +     * Check if the current sign is a valid rancher boots sign.
```suggestion
     * Checks if the current sign is a valid rancher boots sign.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/features/farming/garden/RancherBootsOverlay.java
> +     * Check if the newly opened screen is a sign and if so initialize the rendering.
```suggestion
     * Checks if the newly opened screen is a sign and if so initialize the rendering.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/events/mixins/ScreenHandlerUpdateEventMixin.java
> +     * Get the event instance for ths screen handler instance.
```suggestion
     * Gets the event instance for ths screen handler instance.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/features/farming/garden/RancherBootsOverlay.java
> +     * Create a text for the crop and speed.
```suggestion
     * Creates a text for the crop and speed.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/features/farming/garden/RancherBootsOverlay.java
> +     * Render the speed list onto the sign.
```suggestion
     * Renders the speed list onto the sign.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/features/farming/garden/RancherBootsOverlay.java
> +     * Check if the mouse was clicked on a text and if so, then change the speed to it.
```suggestion
     * Checks if the mouse was clicked on a text and if so, then change the speed to it.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/features/repository/items/item/attributes/Crystal.java
> + * All types of private island crystals
```suggestion
 * All types of private island crystals.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/features/repository/items/item/attributes/GardenLevelRequirement.java
> + * A requirement for a specific garden level
```suggestion
 * A requirement for a specific garden level.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/features/repository/items/item/attributes/GemstoneSlotRequirement.java
> + * @param <T>             The parameter to either have integer or identifier types.
```suggestion
 * One requirement to unlock a gemstone slot.
 *
 * @param requirementType The requirement type.
 * @param value           The item it needs, null when requirementType is COINS.
 * @param amount          The amount it needs.
 * @param <T>             The parameter to either have integer or identifier types.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/features/repository/items/item/attributes/PrivateIsland.java
> + * All private island islands.
```suggestion
 * All private island types.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/features/repository/items/item/attributes/RequirementTypes.java
> +public enum RequirementTypes {
Doc missing

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/mixin/ItemModelOverrides.java
> +     * @return If it should respect others.
```suggestion
     * Whether the item model override should respect the other overrides.
     *
     * @param identifier The override identifier.
     * @return Whether it should respect others.
```

2023-10-30 17:32 UTC, DreamTexX commented on src/main/java/dev/morazzer/cookiesmod/mixin/ItemModelOverrides.java
> +     * @return If the value should match precise.
```suggestion
     * Whether the override should match the precise value instead of exact and higher.
     *
     * @param identifier The identifier.
     * @return Whether the value should match precise.
```

2023-10-30 17:50 UTC, DreamTexX approved these changes
lgtm

2023-10-30 17:58 UTC, merged